### PR TITLE
refactor: migrate to rrule v0.12.0 and track lock file

### PR DESCRIPTION
**Pull request by tomquist**
This updates rrule to the latest version 0.12.0 and also un-ignores the Cargo.lock as suggested for non-libraries here: https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html

While this rrule-rust is a npm library it's not a Cargo library so I think we should have stable dependencies.

### CODE REVIEW

**Comment by tomquist** [comment]
@lsndr Could you create a new v2.x release version with this please?

**Comment by lsndr** [comment]
@tomquist I still have plans to rename something and add more tests. This PR is already release to `next` dist channel, so you can use them as following:

```
npm i rrule-rust@next
#or
npm i rrule-rust@2.0.0-next.2
```

I'll try to finish the rest asap

**Comment by tomquist** [comment]
@lsndr I think it's not on `rrule-rust@2.0.0-next.2` though. `next.2` was released on March 17 but this PR was merged on April 10. Could you create a `next.3` release?

**Comment by lsndr** [comment]
@tomquist you are right, thanks. Released. But looks like there are some problems with semantic-release. Probably it didn't properly publish the new version. I'll investigate it

**Comment by tomquist** [comment]
Thank you!

**Pull request merged**
